name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  luarocks-release:
    name: LuaRocks release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
          GROQ_API_KEY_AI_NVIM: ${{ secrets.GROQ_API_KEY_AI_NVIM }}
        with:
          detailed_description: |
            OpenAI compatible API for Neovim plugins development (Experimental)
          copy_directories: |
            {{ neovim.plugin.dirs }}
  github-release:
    name: GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
